export const teamFeed = [
  {
    teamId: 1,
    exploreId: '관악산',
    title: '관악산 함께가요',
    departureDay: '2024-04-08 14:00',
    ageRange: '20',
    genderRange: '남성',
    description: '',
    kakaoLink: '',
    kakaoPassword: '',
  },
  {
    teamId: 2,
    exploreId: '북한산',
    title: '북한산 가보자고',
    departureDay: '2024-10-05 11:00',
    ageRange: '30',
    genderRange: '남성',
    description: '',
    kakaoLink: '',
    kakaoPassword: '',
  },
  {
    teamId: 3,
    exploreId: '명지산',
    title: '명지산 렛츠고',
    departureDay: '2024-09-12 13:00',
    ageRange: '50',
    genderRange: '여성',
    description: '',
    kakaoLink: '',
    kakaoPassword: '',
  },
  {
    teamId: 4,
    exploreId: '설악산',
    title: '설악산 가실?',
    departureDay: '2024-04-16 14:00',
    ageRange: '30',
    genderRange: '남성',
    description: '',
    kakaoLink: '',
    kakaoPassword: '',
  },
  {
    teamId: 5,
    exploreId: '백운산',
    title: '백운산 같이가요',
    departureDay: '2024-06-15 17:00',
    ageRange: '20',
    genderRange: '여성',
    description: '',
    kakaoLink: '',
    kakaoPassword: '',
  },
  {
    teamId: 6,
    exploreId: '용문산',
    title: '용문산 같이가실분',
    departureDay: '2024-03-27 17:00',
    ageRange: '40',
    genderRange: '여성',
    description: '',
    kakaoLink: '',
    kakaoPassword: '',
  },
];
